### ISSUE TITLE
Bug identified 

### ISSUE THREAD

**Issue by 66037** [coe420spring19/coe420lab2#1]
public class COE420LA2 {

    public static void addFeatureA()
    {
        //Prints feature A added
        System.out.println("Feature A added");
    }
     public static void addFeatureB()
    {
        //Prints feature B added
        System.out.println("Feature B added");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
       addFeatureA();
    }
    
}

**Comment by RashedAlsuwaidi** [comment]
the bug has been fixed :)
